@include('formbuilder::formbuilder.partials.scripts.pages.admin.core')
@include('formbuilder::formbuilder.partials.scripts.pages.admin.dashboard')
@include('formbuilder::formbuilder.partials.scripts.pages.admin.submissions')
@include('formbuilder::formbuilder.partials.scripts.pages.admin.forms')
@include('formbuilder::formbuilder.partials.scripts.pages.admin.editor')
@include('formbuilder::formbuilder.partials.scripts.pages.admin.departments')
@include('formbuilder::formbuilder.partials.scripts.pages.admin.users')
